# Generated by Django 3.2 on 2021-04-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfiles',
            options={'verbose_name': 'CSV file', 'verbose_name_plural': 'CSV files'},
        ),
    ]
