# Generated by Django 3.2 on 2021-04-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_csvfiles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'ordering': ('-total',), 'verbose_name': 'Deals', 'verbose_name_plural': 'Deals'},
        ),
    ]
