# Generated by Django 3.2 on 2021-04-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_deals_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name': 'Deals', 'verbose_name_plural': 'Deals'},
        ),
    ]
